services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "8000:8000"

    init: true
    restart: unless-stopped

    volumes:
      - chroma_data:/app/.chroma_db
      - model_cache:/home/appuser/.cache

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_BASE_URL: http://backend:8000

    environment:
      BACKEND_BASE_URL: http://backend:8000

    ports:
      - "3000:3000"

    depends_on:
      backend:
        condition: service_healthy

    init: true
    restart: unless-stopped


volumes:
  chroma_data:
  model_cache: